package controller;

import javafx.fxml.FXML;
import javafx.scene.control.TreeItem;
import javafx.scene.control.TreeTableView;
import view.Principal;
import javafx.event.ActionEvent;

public class TelaProdutos {
	@FXML private TreeTableView table;
	private Principal login;
	
	// Event Listener on MenuItem.onAction
	@FXML
	public void sair(ActionEvent event) {
		login = new Principal();
		login.telaLogin();
	}
	// Event Listener on TextField.onAction
	@FXML
	public void procurarProduto(ActionEvent event) {
		// TODO Autogenerated
	}
}
